# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import frota_pb2 as frota__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in frota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrotaServiceStub(object):
    """=============================
    Serviço principal da frota
    =============================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Comunicar = channel.stream_stream(
                '/frota.FrotaService/Comunicar',
                request_serializer=frota__pb2.Localizacao.SerializeToString,
                response_deserializer=frota__pb2.Comando.FromString,
                _registered_method=True)
        self.EstimarEntrega = channel.unary_unary(
                '/frota.FrotaService/EstimarEntrega',
                request_serializer=frota__pb2.EntregaRequest.SerializeToString,
                response_deserializer=frota__pb2.EntregaResponse.FromString,
                _registered_method=True)
        self.ConsultarVeiculo = channel.unary_unary(
                '/frota.FrotaService/ConsultarVeiculo',
                request_serializer=frota__pb2.VeiculoRequest.SerializeToString,
                response_deserializer=frota__pb2.Localizacao.FromString,
                _registered_method=True)


class FrotaServiceServicer(object):
    """=============================
    Serviço principal da frota
    =============================
    """

    def Comunicar(self, request_iterator, context):
        """Comunicação bidirecional (streaming):
        O veículo envia continuamente suas localizações,
        e a central responde com comandos em tempo real.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimarEntrega(self, request, context):
        """Consulta unária:
        Retorna uma estimativa de tempo de entrega com base na localização e destino.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarVeiculo(self, request, context):
        """Consulta unária:
        Retorna a localização atual de um veículo específico.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrotaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Comunicar': grpc.stream_stream_rpc_method_handler(
                    servicer.Comunicar,
                    request_deserializer=frota__pb2.Localizacao.FromString,
                    response_serializer=frota__pb2.Comando.SerializeToString,
            ),
            'EstimarEntrega': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimarEntrega,
                    request_deserializer=frota__pb2.EntregaRequest.FromString,
                    response_serializer=frota__pb2.EntregaResponse.SerializeToString,
            ),
            'ConsultarVeiculo': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarVeiculo,
                    request_deserializer=frota__pb2.VeiculoRequest.FromString,
                    response_serializer=frota__pb2.Localizacao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frota.FrotaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('frota.FrotaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrotaService(object):
    """=============================
    Serviço principal da frota
    =============================
    """

    @staticmethod
    def Comunicar(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/frota.FrotaService/Comunicar',
            frota__pb2.Localizacao.SerializeToString,
            frota__pb2.Comando.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimarEntrega(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frota.FrotaService/EstimarEntrega',
            frota__pb2.EntregaRequest.SerializeToString,
            frota__pb2.EntregaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarVeiculo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frota.FrotaService/ConsultarVeiculo',
            frota__pb2.VeiculoRequest.SerializeToString,
            frota__pb2.Localizacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
