# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frota.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rota.proto\x12\x05\x66rota\"m\n\x0bLocalizacao\x12\x12\n\nveiculo_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x12\n\nvelocidade\x18\x05 \x01(\x01\"Q\n\x07\x43omando\x12\x12\n\nveiculo_id\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x10\n\x08mensagem\x18\x03 \x01(\t\x12\x12\n\nprioridade\x18\x04 \x01(\x05\"$\n\x0eVeiculoRequest\x12\x12\n\nveiculo_id\x18\x01 \x01(\t\"Z\n\x0e\x45ntregaRequest\x12\x12\n\nveiculo_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x0f\n\x07\x64\x65stino\x18\x04 \x01(\t\"L\n\x0f\x45ntregaResponse\x12\x16\n\x0etempo_estimado\x18\x01 \x01(\t\x12\x11\n\tcondicoes\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\xc3\x01\n\x0c\x46rotaService\x12\x33\n\tComunicar\x12\x12.frota.Localizacao\x1a\x0e.frota.Comando(\x01\x30\x01\x12?\n\x0e\x45stimarEntrega\x12\x15.frota.EntregaRequest\x1a\x16.frota.EntregaResponse\x12=\n\x10\x43onsultarVeiculo\x12\x15.frota.VeiculoRequest\x1a\x12.frota.Localizacaob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCALIZACAO']._serialized_start=22
  _globals['_LOCALIZACAO']._serialized_end=131
  _globals['_COMANDO']._serialized_start=133
  _globals['_COMANDO']._serialized_end=214
  _globals['_VEICULOREQUEST']._serialized_start=216
  _globals['_VEICULOREQUEST']._serialized_end=252
  _globals['_ENTREGAREQUEST']._serialized_start=254
  _globals['_ENTREGAREQUEST']._serialized_end=344
  _globals['_ENTREGARESPONSE']._serialized_start=346
  _globals['_ENTREGARESPONSE']._serialized_end=422
  _globals['_FROTASERVICE']._serialized_start=425
  _globals['_FROTASERVICE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
